# This file was generated by GoReleaser. DO NOT EDIT.
cask "jiracli" do
  version "0.2.0"

  on_macos do
    on_intel do
      sha256 "a4568dbef8656db0c6938efe6cc2e3984411472a8e8be6f55f5ba306cc9373c7"
      url "https://github.com/cgrossde/jiracli/releases/download/v#{version}/jiracli_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "75f855f1d8c39236364d1d4f7f0a261d5c85e4c92dd7c6a354e78fd5a03b2d59"
      url "https://github.com/cgrossde/jiracli/releases/download/v#{version}/jiracli_darwin_arm64.tar.gz"
    end
  end

  name "jiracli"
  desc "Easy, agent-friendly & scriptable Jira access"
  homepage "https://github.com/cgrossde/jiracli"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "jiracli"
  bash_completion "completions/jiracli.bash"
  fish_completion "completions/jiracli.fish"
  zsh_completion "completions/jiracli.zsh"

  postflight do
    system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/jiracli"]
  end

  # No zap stanza required

end
