# This file was generated by GoReleaser. DO NOT EDIT.
cask "jiracli" do
  version "0.2.2"

  on_macos do
    on_arm do
      sha256 "6834814cb0d865a57b3862021b22f7fe5c4282dfe996ae93d90dd4e0b246bee2"
      url "https://github.com/cgrossde/jiracli/releases/download/v#{version}/jiracli_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "26adc6c87d1ac7d466ef7d361a5c313fdbd841f417665cce95ecf118444fcce8"
      url "https://github.com/cgrossde/jiracli/releases/download/v#{version}/jiracli_darwin_amd64.tar.gz"
    end
  end

  name "jiracli"
  desc "Easy, agent-friendly & scriptable Jira access"
  homepage "https://github.com/cgrossde/jiracli"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "jiracli"
  bash_completion "completions/jiracli.bash"
  fish_completion "completions/jiracli.fish"
  zsh_completion "completions/jiracli.zsh"

  postflight do
    system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/jiracli"]
  end

  # No zap stanza required
end
