# This file was generated by GoReleaser. DO NOT EDIT.
cask "jiracli" do
  version "0.1.1"

  on_macos do
    on_intel do
      sha256 "1d4c4f2a0444927cf5573128bbb1b713595960a6f0d7bd8e4fa4db85a642a6dd"
      url "https://github.com/cgrossde/jiracli/releases/download/v#{version}/jiracli_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "5d6f73978ec318a776b729b3507442f58046a81539007e1d3eb74dc334a42994"
      url "https://github.com/cgrossde/jiracli/releases/download/v#{version}/jiracli_darwin_arm64.tar.gz"
    end
  end

  name "jiracli"
  desc "Easy, agent-friendly & scriptable Jira access"
  homepage "https://github.com/cgrossde/jiracli"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "jiracli"
  bash_completion "completions/jiracli.bash"
  fish_completion "completions/jiracli.fish"
  zsh_completion "completions/jiracli.zsh"

  postflight do
    system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/jiracli"]
  end

  # No zap stanza required

end
