# typed: strict
# frozen_string_literal: true

# This file is auto-generated by the PeekMD release workflow. Do not edit by hand.
cask "peekmd" do
  version "0.1.1"
  sha256 "690bba2b8571a49522b9fa6ca83edc88e99250d9ca4dcbd9bf960914eb39aa69"

  url "https://github.com/cgrossde/PeekMD/releases/download/v#{version}/PeekMD_#{version}_aarch64.dmg"
  desc "GitHub-flavored Markdown previewer"
  homepage "https://github.com/cgrossde/PeekMD"

  livecheck do
    skip "Auto-generated on release."
  end

  depends_on macos: ">= :sonoma"
  depends_on arch: :arm64

  app "PeekMD.app"
  binary "#{appdir}/PeekMD.app/Contents/MacOS/peekmd-cli"

  postflight do
    system_command "/usr/bin/xattr",
                   args: ["-dr", "com.apple.quarantine", "#{appdir}/PeekMD.app"]
  end

  zap trash: [
    "~/Library/Application Support/com.peekmd.desktop",
    "~/Library/Caches/com.peekmd.desktop",
    "~/Library/Preferences/com.peekmd.desktop.plist",
    "~/Library/Saved Application State/com.peekmd.desktop.savedState",
    "~/Library/WebKit/com.peekmd.desktop",
  ]
end
