# This file was generated by GoReleaser. DO NOT EDIT.
cask "slackcli" do
  version "0.1.1"

  on_macos do
    on_intel do
      sha256 "105467598fc267427406c768952357a8fd59225f92218baa2ccc15241a1f9ac5"
      url "https://github.com/cgrossde/slackcli/releases/download/v#{version}/slackcli_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "fafa3778002476f239e82886a47a9c07b628f1eaaadfdce57469f1d2b1a03d30"
      url "https://github.com/cgrossde/slackcli/releases/download/v#{version}/slackcli_darwin_arm64.tar.gz"
    end
  end

  name "slackcli"
  desc "Slack CLI optimized for usage by LLMs or in scripts"
  homepage "https://github.com/cgrossde/slackcli"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "slackcli"
  bash_completion "completions/slackcli.bash"
  fish_completion "completions/slackcli.fish"
  zsh_completion "completions/slackcli.zsh"

  postflight do
    system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/slackcli"]
  end

  # No zap stanza required

end
