# This file was generated by GoReleaser. DO NOT EDIT.
cask "slackcli" do
  version "0.1.3"

  on_macos do
    on_intel do
      sha256 "e72168fa588264706f3e01708a44e077a1391b1ee14c5691ed8149e05fef142e"
      url "https://github.com/cgrossde/slackcli/releases/download/v#{version}/slackcli_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "0ab5e74b07474dd375d5a739f119be2fe7b75c9982fbcb3da80b8b05bbf34a47"
      url "https://github.com/cgrossde/slackcli/releases/download/v#{version}/slackcli_darwin_arm64.tar.gz"
    end
  end

  name "slackcli"
  desc "Slack CLI optimized for usage by LLMs or in scripts"
  homepage "https://github.com/cgrossde/slackcli"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "slackcli"
  bash_completion "completions/slackcli.bash"
  fish_completion "completions/slackcli.fish"
  zsh_completion "completions/slackcli.zsh"

  postflight do
    system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/slackcli"]
  end

  # No zap stanza required

end
