# This file was generated by GoReleaser. DO NOT EDIT.
cask "slackcli" do
  version "0.1.0"

  on_macos do
    on_intel do
      sha256 "70a4367a0a7484ee253e6aa34e50fa994c526c055f1ba7d2bc9a890836c2eda1"
      url "https://github.com/cgrossde/slackcli/releases/download/v#{version}/slackcli_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "e6402fe6276cad821e5acfe7dad8c6d171514d4437ad21f52e2c5f5a886a99f6"
      url "https://github.com/cgrossde/slackcli/releases/download/v#{version}/slackcli_darwin_arm64.tar.gz"
    end
  end

  name "slackcli"
  desc "Slack CLI optimized for usage by LLMs or in scripts"
  homepage "https://github.com/cgrossde/slackcli"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "slackcli"

  postflight do
    system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/slackcli"]
  end
  generate_completions_from_executable "bin/slackcli", "completion",
    shell_parameter_format: :cobra

  # No zap stanza required

end
